# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "uas" "sd_mod" "sr_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  boot.initrd.secrets."/key" = "/etc/luks-keys/key";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/87c87997-7cd1-4fbe-96ed-def989799073";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."nixos" = {
    device = "/dev/disk/by-uuid/cbfa11ef-4ca6-4f0e-a75c-9462431dc6e6";
    keyFile = "/key";
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F768-ADF1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  boot.initrd.luks.devices."swap" = {
    device = "/dev/disk/by-uuid/9750fbcf-85e8-48d1-9218-e99b6125d295";
    keyFile = "/key";
  };

  swapDevices =
    [ { device = "/dev/mapper/swap"; }
    ];

  fileSystems."/mnt/mass" = {
    device = "/dev/mapper/mass";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."mass" = {
    device = "/dev/disk/by-uuid/dd3e061d-0305-4802-a53b-9eb5bd98b5a5";
    keyFile = "/key";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  services.logind.settings.Login = {
    HandleLidSwitch = "ignore";
    HandleLidSwitchExternalPower = "ignore";
  };
}
