
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e9894807-ac7a-45a8-baba-eff79fd0482c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a976dfd3-5b7b-4662-80ee-f569c32ee523".device = "/dev/disk/by-uuid/a976dfd3-5b7b-4662-80ee-f569c32ee523";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/D404-FBCE";
      fsType = "vfat";
    };
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8079163c-2544-4ba2-b0d8-c03aaa0fcdf7";
      fsType = "ext4";
    };

  fileSystems."/mnt/storage" =
    { device = "/dev/disk/by-uuid/8470403b-52aa-4fe9-b538-ddcef99bc887";
      fsType = "ext4";
    };
  boot.initrd.luks.devices."luks-16951942-652b-46b2-9c86-a2059e9c46a9".device = "/dev/disk/by-uuid/16951942-652b-46b2-9c86-a2059e9c46a9";

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.bluetooth.enable = true;
}
