# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e85b03bb-71a6-4a14-b968-e60fa8c38100";
      fsType = "btrfs";
      options = [ "subvol=root" "noatime" ];
    };

  boot.initrd.luks.devices."nix".device = "/dev/disk/by-uuid/3a272a66-b265-43d2-b388-72b96ec6a63b";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e85b03bb-71a6-4a14-b968-e60fa8c38100";
      fsType = "btrfs";
      options = [ "subvol=home" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/e85b03bb-71a6-4a14-b968-e60fa8c38100";
      fsType = "btrfs";
      options = [ "subvol=nix" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/86BE-3516";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/storage/JS" =
    { device = "/dev/mapper/storage";
      fsType = "btrfs";
      options = [ "subvol=JS" "noatime" ];
    };
  fileSystems."/mnt/storage/games" =
    { device = "/dev/mapper/storage";
      fsType = "btrfs";
      options = [ "subvol=games" "noatime" ];
    };
  
  boot.initrd.luks.devices."storage".device = "/dev/disk/by-uuid/66749e7c-759c-455a-aa55-b300874ae120";
  

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp11s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp12s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # ddcutil brightness
  hardware.i2c.enable = true;
  services.udev.extraRules = ''
    SUBSYSTEM=="i2c-dev", KERNEL=="i2c-6", TAG+="uaccess"
  '';

  hardware.bluetooth.enable = true;
}
